UPDATE shows SET title = "How I Met Your Mother" WHERE id = 1;
UPDATE shows SET title = "The Untamed" WHERE title = "the Untamed";
UPDATE shows SET title = "Arrow" WHERE title = "arrow";
UPDATE shows SET title = "Avatar: The Last Airbender" WHERE title = "Avatar The Last Airbender";
UPDATE shows SET title = "Community" WHERE title = "community";
UPDATE shows SET title = "Friends" WHERE title = "friends";
UPDATE shows SET title = "The Bachelorette" WHERE title = "the bachelorette";
UPDATE shows SET title  = "The Crown" WHERE title = "The CROWN";
UPDATE shows SET title = "Game of Thrones" WHERE title = "GoT";
UPDATE shows SET title = "Adventure Time" WHERE title = "adventure time";
UPDATE shows SET title = "Squid Game" WHERE title = "squid game";
UPDATE shows SET title = "Criminal Minds" WHERE title = "criminal minds";
UPDATE shows SET title = "The Office" WHERE title = "the office";
UPDATE shows SET title = "Family Guy" WHERE title = "family guy";
UPDATE shows SET title = "Billions" WHERE title = "billions";
UPDATE shows SET title = "The Office" WHERE title = "Thevoffice" or title = "The office";
UPDATE shows SET title = "Grey's Anatomy" WHERE title = "Grey's anatomy";
UPDATE shows SET title = "Gilmore Girls" WHERE title = "Gilmore girls";
UPDATE shows SET title = "Brooklyn Nine-Nine" WHERE title = "brooklyn 99" or title = "B99";
UPDATE shows SET title = "Sherlock Holmes" WHERE title = "sherlock holmes";
